/*
 * VOS PAGE 1.0 — strict application-page language.
 * .page is deliberately NOT VOS source. It is a capability-scoped, declarative
 * UI + bounded action language with hard wall-clock and operation budgets.
 */

const PAGE_VERSION='1.0';
export const PAGE_LIMITS=Object.freeze({
  startupMs:500, renderMs:16, eventMs:50, actionMs:100, totalMs:5000,
  ops:100000, memoryBytes:32*1024*1024, maxActions:128, maxViewNodes:512,
  maxState:128, maxDepth:12, maxPagesPerFile:32, maxSourceBytes:256*1024,
  maxHandlerCode:4096, maxViolations:1
});
export const PAGE_PERMISSIONS=Object.freeze(new Set([
  'ui.draw','ui.input','storage.read','storage.write','events.emit','events.listen',
  'notifications.post','clipboard.read','clipboard.write','filesystem.read',
  'network.request','system.stats'
]));

function diag(level,code,message,t,file){return {level,code,message,file:t?.file||file,line:t?.line||1,column:t?.column||1};}
class Lexer{
  constructor(file,src){this.file=file;this.s=src;this.i=0;this.line=1;this.col=1;this.ds=[];}
  p(n=0){return this.s[this.i+n]??'\0';} take(){const c=this.p();if(c==='\0')return c;this.i++;if(c==='\n'){this.line++;this.col=1}else this.col++;return c;}
  t(kind,text,l,c){return {kind,text,file:this.file,line:l,column:c};}
  skip(){for(;;){while(/\s/.test(this.p())&&this.p()!=='\0')this.take();if(this.p()==='/'&&this.p(1)==='/'){while(this.p()!=='\n'&&this.p()!=='\0')this.take();continue;}if(this.p()==='/'&&this.p(1)==='*'){const l=this.line,c=this.col;this.take();this.take();let ok=false;while(this.p()!=='\0'){if(this.p()==='*'&&this.p(1)==='/'){this.take();this.take();ok=true;break}this.take()}if(!ok)this.ds.push(diag('error','PAGE-E0001','unterminated block comment',{file:this.file,line:l,column:c},this.file));continue;}break}}
  lex(){const o=[];while(this.p()!=='\0'){this.skip();if(this.p()==='\0')break;const l=this.line,c=this.col,ch=this.p();if(/[A-Za-z_$]/.test(ch)){let s='';while(/[A-Za-z0-9_$.-]/.test(this.p()))s+=this.take();o.push(this.t('id',s,l,c));continue}if(/[0-9]/.test(ch)){let s='';while(/[A-Za-z0-9_.]/.test(this.p()))s+=this.take();o.push(this.t('num',s,l,c));continue}if(ch==='"'||ch==="'"){const q=this.take();let s=q,esc=false,ok=false;while(this.p()!=='\0'){const x=this.take();s+=x;if(esc){esc=false;continue}if(x==='\\'){esc=true;continue}if(x===q){ok=true;break}}if(!ok)this.ds.push(diag('error','PAGE-E0002','unterminated string',{file:this.file,line:l,column:c},this.file));o.push(this.t('str',s,l,c));continue}let op='';for(const x of ['->','<=','>=','==','!=','::'])if(this.s.startsWith(x,this.i)){op=x;break}if(op){for(let z=0;z<op.length;z++)this.take();o.push(this.t('sym',op,l,c))}else o.push(this.t('sym',this.take(),l,c));}o.push(this.t('end','',this.line,this.col));return o;}
}
function unq(s){if(typeof s!=='string')return s;if((s[0]==='"'&&s.at(-1)==='"')||(s[0]==="'"&&s.at(-1)==="'")){try{return JSON.parse(s[0]==="'"?'"'+s.slice(1,-1).replaceAll('"','\\"')+'"':s)}catch{return s.slice(1,-1)}}return s}
function num(t){const s=String(t?.text??t).replaceAll('_','');const units={ms:1,s:1000,KiB:1024,MiB:1048576,GiB:1073741824};for(const [u,m] of Object.entries(units))if(s.endsWith(u)){const n=Number(s.slice(0,-u.length));return Number.isFinite(n)?n*m:NaN}return Number(s)}
function literal(t){if(!t)return null;if(t.kind==='str')return unq(t.text);if(t.text==='true')return true;if(t.text==='false')return false;if(t.text==='null')return null;if(t.kind==='num')return num(t);return {state:t.text};}

class Parser{
  constructor(file,tokens){this.file=file;this.t=tokens;this.i=0;this.ds=[];this.viewCount=0;}
  p(n=0){return this.t[this.i+n]??this.t.at(-1)} end(){return this.p().kind==='end'} take(){return this.end()?this.p():this.t[this.i++]} match(x){return this.p().text===x} consume(x){if(this.match(x)){this.i++;return true}return false}
  err(code,msg,t=this.p()){this.ds.push(diag('error',code,msg,t,this.file))} warn(code,msg,t=this.p()){this.ds.push(diag('warning',code,msg,t,this.file))}
  need(x,code='PAGE-E0100'){if(!this.consume(x)){this.err(code,`expected '${x}'`);return false}return true}
  id(code='PAGE-E0101'){const t=this.take();if(t.kind!=='id'){this.err(code,'expected identifier',t);return ''}return t.text}
  str(code='PAGE-E0102'){const t=this.take();if(t.kind!=='str'){this.err(code,'expected quoted string',t);return ''}return String(unq(t.text))}
  semi(){this.need(';','PAGE-E0103')}
  blockStart(){return this.need('{','PAGE-E0104')}
  budget(){const b={startupMs:250,renderMs:12,eventMs:30,actionMs:50,totalMs:2000,ops:12000,memoryBytes:4*1024*1024};this.blockStart();while(!this.end()&&!this.match('}')){const key=this.id();this.need('<=','PAGE-E0200');const t=this.take(),v=num(t);this.semi();const map={startup:'startupMs',render:'renderMs',event:'eventMs',action:'actionMs',total:'totalMs',ops:'ops',memory:'memoryBytes'};if(!map[key])this.err('PAGE-E0201',`unknown budget '${key}'`,t);else if(!Number.isFinite(v)||v<=0)this.err('PAGE-E0202',`budget '${key}' must be positive`,t);else b[map[key]]=Math.trunc(v)}this.need('}','PAGE-E0203');return b;}
  permissions(){const out=[];this.blockStart();while(!this.end()&&!this.match('}')){const t=this.take();if(t.kind!=='id'){this.err('PAGE-E0300','permission must be an identifier',t);while(!this.end()&&!this.consume(';')&&!this.match('}'))this.take();continue}const p=t.text;this.semi();if(!PAGE_PERMISSIONS.has(p))this.err('PAGE-E0301',`permission '${p}' is not available to PAGE`,t);else if(!out.includes(p))out.push(p)}this.need('}','PAGE-E0302');return out;}
  state(){const out={};this.blockStart();while(!this.end()&&!this.match('}')){const t=this.p(),name=this.id();this.need(':','PAGE-E0400');const type=this.id();if(!['string','i32','u32','f64','bool'].includes(type))this.err('PAGE-E0401',`unsupported state type '${type}'`,t);this.need('=','PAGE-E0402');const v=literal(this.take());this.semi();if(v&&typeof v==='object')this.err('PAGE-E0403','state initializers must be literals',t);out[name]={type,value:v};if(Object.keys(out).length>PAGE_LIMITS.maxState)this.err('PAGE-E0404',`page exceeds ${PAGE_LIMITS.maxState} state slots`,t)}this.need('}','PAGE-E0405');return out;}
  viewNodes(depth=0){const out=[];if(depth>PAGE_LIMITS.maxDepth){this.err('PAGE-E0500',`view nesting exceeds ${PAGE_LIMITS.maxDepth}`);return out}this.blockStart();while(!this.end()&&!this.match('}')){const t=this.p(),kind=this.id();this.viewCount++;if(this.viewCount>PAGE_LIMITS.maxViewNodes)this.err('PAGE-E0501',`view exceeds ${PAGE_LIMITS.maxViewNodes} nodes`,t);if(['row','column','card'].includes(kind)){out.push({kind,children:this.viewNodes(depth+1)});continue}if(kind==='divider'){this.semi();out.push({kind});continue}if(kind==='spacer'){const v=num(this.take());this.semi();out.push({kind,size:Number.isFinite(v)?v:12});continue}if(['heading','text','badge'].includes(kind)){let text='';let bind='';if(this.p().kind==='str')text=this.str();else if(this.consume('bind'))bind=this.id();else this.err('PAGE-E0502',`${kind} requires a string or 'bind <state>'`,t);this.semi();out.push({kind,text,bind});continue}if(kind==='metric'){const label=this.str();this.need('bind','PAGE-E0503');const bind=this.id();this.semi();out.push({kind,label,bind});continue}if(kind==='button'){const label=this.str();this.need('->','PAGE-E0504');const action=this.id();this.semi();out.push({kind,label,action});continue}this.err('PAGE-E0505',`unknown view node '${kind}'`,t);while(!this.end()&&!this.consume(';')&&!this.match('}'))this.take()}this.need('}','PAGE-E0506');return out;}
  ops(){const out=[];this.blockStart();while(!this.end()&&!this.match('}')){const t=this.p(),op=this.id();if(op==='set'){const name=this.id();this.need('=','PAGE-E0600');const value=literal(this.take());this.semi();out.push({op,name,value});continue}if(op==='inc'){const name=this.id(),value=num(this.take());this.semi();out.push({op,name,value:Number.isFinite(value)?value:1});continue}if(op==='toggle'){const name=this.id();this.semi();out.push({op,name});continue}if(op==='emit'){const event=this.str();this.semi();out.push({op,event});continue}if(op==='notify'){const title=this.str(),message=this.str();this.semi();out.push({op,title,message});continue}if(op==='navigate'){const route=this.str();this.semi();out.push({op,route});continue}if(op==='invalidate'){this.semi();out.push({op});continue}if(op==='storage.set'){const key=this.str();const value=literal(this.take());this.semi();out.push({op,key,value});continue}if(op==='storage.get'){const key=this.str();this.need('->','PAGE-E0601');const name=this.id();this.semi();out.push({op,key,name});continue}this.err('PAGE-E0602',`operation '${op}' is not permitted in PAGE`,t);while(!this.end()&&!this.consume(';')&&!this.match('}'))this.take()}this.need('}','PAGE-E0603');return out;}
  handler(kind){const start=this.p();let name=kind==='action'?this.id():this.id();this.need('timeout','PAGE-E0700');const timeoutMs=num(this.take());this.need('ops','PAGE-E0701');const opsLimit=num(this.take());const code=this.ops();return {kind,name,timeoutMs:Math.trunc(timeoutMs),opsLimit:Math.trunc(opsLimit),code,span:start};}
  page(appId){const t=this.p(),name=this.id(),route=this.consume('route')?this.str():`/${name.toLowerCase()}`;this.blockStart();let budget=null,permissions=null,state={},view=null;const actions={},events={};while(!this.end()&&!this.match('}')){const k=this.id();if(k==='budget'){budget=this.budget();continue}if(k==='permissions'){permissions=this.permissions();continue}if(k==='state'){state=this.state();continue}if(k==='view'){view=this.viewNodes();continue}if(k==='action'){const h=this.handler('action');if(actions[h.name])this.err('PAGE-E0800',`duplicate action '${h.name}'`,h.span);actions[h.name]=h;continue}if(k==='on'){const h=this.handler('event');if(events[h.name])this.err('PAGE-E0801',`duplicate event handler '${h.name}'`,h.span);events[h.name]=h;continue}this.err('PAGE-E0802',`unknown page section '${k}'`,t)}this.need('}','PAGE-E0803');if(!budget)this.err('PAGE-E0804',`page '${name}' requires a budget block`,t);if(!permissions)this.err('PAGE-E0805',`page '${name}' requires a permissions block`,t);if(!view)this.err('PAGE-E0806',`page '${name}' requires a view block`,t);return {language:'VOS-PAGE',version:PAGE_VERSION,appId,name,route,budget:budget||{},permissions:permissions||[],state,view:view||[],actions,events};}
  parse(){this.need('@','PAGE-E0105');this.need('page','PAGE-E0106');const version=this.take().text;this.semi();if(version!==PAGE_VERSION)this.err('PAGE-E0107',`PAGE version ${version} is unsupported; expected ${PAGE_VERSION}`);this.need('app','PAGE-E0108');const appId=this.p().kind==='str'?this.str():this.id();this.semi();const pages=[];while(!this.end()){if(!this.consume('page')){this.err('PAGE-E0109',`expected 'page' declaration, found '${this.p().text}'`);this.take();continue}pages.push(this.page(appId));if(pages.length>PAGE_LIMITS.maxPagesPerFile)this.err('PAGE-E0111',`.page file exceeds ${PAGE_LIMITS.maxPagesPerFile} page declarations`);}if(!pages.length)this.err('PAGE-E0110','a .page file must contain at least one page');return {language:'VOS-PAGE',version,appId,pages,diagnostics:this.ds};}
}

function validateDescriptor(ast,file,appCaps=[]){const ds=ast.diagnostics,routeSet=new Set(),capSet=new Set(appCaps||[]);const opPermission={'emit':'events.emit','notify':'notifications.post','storage.set':'storage.write','storage.get':'storage.read'};for(const p of ast.pages){const b=p.budget||{};for(const [key,limit] of Object.entries({startupMs:PAGE_LIMITS.startupMs,renderMs:PAGE_LIMITS.renderMs,eventMs:PAGE_LIMITS.eventMs,actionMs:PAGE_LIMITS.actionMs,totalMs:PAGE_LIMITS.totalMs,ops:PAGE_LIMITS.ops,memoryBytes:PAGE_LIMITS.memoryBytes})){if((b[key]??0)>limit)ds.push(diag('error','PAGE-E0900',`${key}=${b[key]} exceeds hard PAGE limit ${limit}`,null,file));}
    if(routeSet.has(p.route))ds.push(diag('error','PAGE-E0901',`duplicate route '${p.route}'`,null,file));routeSet.add(p.route);
    for(const perm of p.permissions)if(appCaps.length&&!capSet.has(perm))ds.push(diag('error','PAGE-E0902',`page requests '${perm}' but app manifest does not grant it`,null,file));
    const handlers=[...Object.entries(p.actions).map(([name,h])=>['action',name,h]),...Object.entries(p.events).map(([name,h])=>['event',name,h])];
    if(handlers.length>PAGE_LIMITS.maxActions)ds.push(diag('error','PAGE-E0909',`page defines ${handlers.length} handlers; hard limit is ${PAGE_LIMITS.maxActions}`,null,file));
    for(const [kind,name,h] of handlers){const cap=kind==='action'?'actionMs':(name==='mount'?'startupMs':'eventMs');if(h.timeoutMs<=0||h.timeoutMs>b[cap])ds.push(diag('error',kind==='action'?'PAGE-E0903':'PAGE-E0905',`${kind} '${name}' timeout ${h.timeoutMs}ms exceeds ${cap} budget ${b[cap]}ms`,h.span,file));if(h.opsLimit<=0||h.opsLimit>b.ops)ds.push(diag('error',kind==='action'?'PAGE-E0904':'PAGE-E0906',`${kind} '${name}' ops ${h.opsLimit} exceeds page budget ${b.ops}`,h.span,file));if(h.code.length>PAGE_LIMITS.maxHandlerCode||h.code.length>h.opsLimit)ds.push(diag('error','PAGE-E0910',`${kind} '${name}' contains ${h.code.length} compiled operations but permits only ${Math.min(PAGE_LIMITS.maxHandlerCode,h.opsLimit)} operations`,h.span,file));for(const ins of h.code){if(['set','inc','toggle'].includes(ins.op)&&!p.state[ins.name])ds.push(diag('error','PAGE-E0911',`${kind} '${name}' writes unknown state '${ins.name}'`,h.span,file));if(ins.op==='storage.get'&&!p.state[ins.name])ds.push(diag('error','PAGE-E0912',`${kind} '${name}' stores into unknown state '${ins.name}'`,h.span,file));const req=opPermission[ins.op];if(req&&!p.permissions.includes(req))ds.push(diag('error','PAGE-E0913',`${kind} '${name}' uses '${ins.op}' but PAGE permission '${req}' is not declared`,h.span,file));}}
    const actionNames=new Set(Object.keys(p.actions));let hasInteractive=false;const walk=nodes=>{for(const n of nodes){if(n.bind&&!p.state[n.bind])ds.push(diag('error','PAGE-E0907',`view binds unknown state '${n.bind}'`,null,file));if(n.action){hasInteractive=true;if(!actionNames.has(n.action))ds.push(diag('error','PAGE-E0908',`button references unknown action '${n.action}'`,null,file));}if(n.children)walk(n.children)}};walk(p.view);if(!p.permissions.includes('ui.draw'))ds.push(diag('error','PAGE-E0914',`PAGE view requires mandatory permission 'ui.draw'`,null,file));if(hasInteractive&&!p.permissions.includes('ui.input'))ds.push(diag('error','PAGE-E0915',`interactive PAGE view requires permission 'ui.input'`,null,file));
  }return ds;}

export class VOSPageCompiler{
  compile(source,{file='<app>.page',appCapabilities=[]}={}){source=String(source??'');const lx=new Lexer(file,source),ps=new Parser(file,lx.lex()),ast=ps.parse();ast.diagnostics.unshift(...lx.ds);const sourceBytes=new TextEncoder().encode(source).byteLength;if(sourceBytes>PAGE_LIMITS.maxSourceBytes)ast.diagnostics.unshift(diag('error','PAGE-E0003',`.page source is ${sourceBytes} bytes; hard limit is ${PAGE_LIMITS.maxSourceBytes}`,null,file));validateDescriptor(ast,file,appCapabilities);const success=!ast.diagnostics.some(d=>d.level==='error');return {success,diagnostics:ast.diagnostics,ast,pages:success?ast.pages:[],file,sourceBytes};}
}
export function compilePage(source,options={}){return new VOSPageCompiler().compile(source,options);}

function now(){return globalThis.performance?.now?.()??Date.now()}
function resolveValue(v,state){return v&&typeof v==='object'&&'state'in v?state[v.state]:v}
export class VOSPageTimeoutError extends Error{constructor(msg,detail={}){super(msg);this.name='VOSPageTimeoutError';Object.assign(this,detail)}}
export class VOSPageSandbox{
  constructor(runtime){this.runtime=runtime;this.files=new Map();this.pagesByApp=new Map();this.instances=new WeakMap();this.violations=[];}
  install(files=[]){this.files.clear();this.pagesByApp.clear();for(const f of files){this.files.set(f.file,f);for(const page of f.pages||[]){const a=this.pagesByApp.get(page.appId)||[];a.push({...page,file:f.file});this.pagesByApp.set(page.appId,a)}}return this.files.size;}
  pages(appId){return this.pagesByApp.get(appId)||[]}
  page(appId,routeOrFile=''){const all=this.pages(appId);return all.find(p=>p.file===routeOrFile||p.route===routeOrFile||p.name===routeOrFile)||all[0]||null}
  instance(window,app){let x=this.instances.get(window);if(x)return x;const page=this.page(app.id,app.entryPage||app.file||'');if(!page)return null;const state={};for(const [k,v] of Object.entries(page.state||{}))state[k]=v.value;x={app,page,state,route:page.route,created:now(),ops:0,renderMs:0,totalExecMs:0,hits:[]};this.instances.set(window,x);this.runEvent(x,'mount').catch(()=>{});return x;}
  _violate(x,type,message){x.violationCount=(x.violationCount||0)+1;x.suspended=x.violationCount>=PAGE_LIMITS.maxViolations;const v={time:Date.now(),appId:x.app.id,page:x.page.name,type,message,violationCount:x.violationCount,suspended:x.suspended};this.violations.push(v);this.runtime.events.emit('page:violation',v);return new VOSPageTimeoutError(message,v)}
  _requirePagePerm(x,perm){if(!x.page.permissions?.includes(perm))throw this._violate(x,'permission',`PAGE did not declare required permission '${perm}'`);this.runtime.permissions.require(x.app.id,perm);return true}
  async runEvent(x,name){const h=x.page.events?.[name];if(!h)return false;return this.runHandler(x,h,`event:${name}`)}
  async runAction(x,name){const h=x.page.actions?.[name];if(!h)throw new Error(`unknown PAGE action ${name}`);return this.runHandler(x,h,`action:${name}`)}
  async runHandler(x,h,label){if(x.suspended)throw new VOSPageTimeoutError(`PAGE '${x.page.name}' is quarantined after a policy violation`,{appId:x.app.id,page:x.page.name,type:'quarantined'});const started=now(),deadline=started+h.timeoutMs;let ops=0;for(const ins of h.code){ops++;x.ops++;if(ops>h.opsLimit)throw this._violate(x,'ops',`${label} exceeded ${h.opsLimit} operations`);if(now()>deadline)throw this._violate(x,'timeout',`${label} exceeded ${h.timeoutMs}ms wall-clock budget`);switch(ins.op){case'set':x.state[ins.name]=resolveValue(ins.value,x.state);break;case'inc':x.state[ins.name]=Number(x.state[ins.name]||0)+Number(ins.value||0);break;case'toggle':x.state[ins.name]=!x.state[ins.name];break;case'emit':this._requirePagePerm(x,'events.emit');this.runtime.events.emit(ins.event,{appId:x.app.id,page:x.page.name,state:{...x.state}});break;case'notify':this._requirePagePerm(x,'notifications.post');this.runtime.notifications.push(x.app.id,ins.title,ins.message);break;case'navigate':{const p=this.page(x.app.id,ins.route);if(p){x.page=p;x.route=p.route;for(const [k,v] of Object.entries(p.state||{}))if(!(k in x.state))x.state[k]=v.value;}break}case'invalidate':this.runtime.desktop.invalidate();break;case'storage.set':this._requirePagePerm(x,'storage.write');this.runtime.appStorage.set(x.app.id,ins.key,resolveValue(ins.value,x.state));break;case'storage.get':this._requirePagePerm(x,'storage.read');x.state[ins.name]=this.runtime.appStorage.get(x.app.id,ins.key,null);break;default:throw new Error(`unsupported PAGE opcode ${ins.op}`)}}const elapsed=now()-started;x.totalExecMs+=elapsed;if(elapsed>h.timeoutMs)throw this._violate(x,'timeout',`${label} completed after ${elapsed.toFixed(2)}ms > ${h.timeoutMs}ms`);const stateBytes=new TextEncoder().encode(JSON.stringify(x.state)).byteLength;if(stateBytes>x.page.budget.memoryBytes)throw this._violate(x,'memory',`${label} state uses ${stateBytes} bytes > ${x.page.budget.memoryBytes}`);if(x.totalExecMs>x.page.budget.totalMs)throw this._violate(x,'total-time',`${label} pushed cumulative PAGE execution above ${x.page.budget.totalMs}ms`);this.runtime.events.emit('page:handler',{appId:x.app.id,page:x.page.name,label,elapsedMs:elapsed,ops});this.runtime.desktop.invalidate();return true;}
  render(ctx){const x=this.instance(ctx.window,ctx.app);if(!x){ctx.g.text(ctx.x,ctx.y,'PAGE NOT FOUND',0xff8191ff,3,ctx.cw);return}if(x.suspended){ctx.g.text(ctx.x,ctx.y,'PAGE QUARANTINED',0xff8191ff,3,ctx.cw);ctx.g.text(ctx.x,ctx.y+42,'A strict PAGE rule or execution budget was violated.',0xffb0baff,2,ctx.cw);ctx.g.text(ctx.x,ctx.y+72,'Close and reopen the app after correcting the PAGE source.',0x91a9c3ff,2,ctx.cw);return}const started=now(),deadline=started+x.page.budget.renderMs;x.hits=[];let yy=ctx.y;const line=(text,size=2,color=0xd8e5f4ff)=>{ctx.g.text(ctx.x+8,yy,String(text),color,size,ctx.cw-16);yy+=size>=3?34:24};const walk=(nodes,depth=0)=>{for(const n of nodes){if(now()>deadline)throw this._violate(x,'render-timeout',`render exceeded ${x.page.budget.renderMs}ms`);if(n.kind==='heading')line(n.bind?x.state[n.bind]:n.text,3,ctx.app.accent||0x7fd6ffff);else if(n.kind==='text')line(n.bind?x.state[n.bind]:n.text);else if(n.kind==='badge'){ctx.g.fillRect(ctx.x+8,yy,Math.min(ctx.cw-16,220),26,0x173652ff);line(n.text,2,0x9fe3ffff)}else if(n.kind==='divider'){ctx.g.fillRect(ctx.x+8,yy+4,ctx.cw-16,1,0x355274ff);yy+=18}else if(n.kind==='spacer')yy+=Math.max(0,Math.min(80,n.size||12));else if(n.kind==='metric'){ctx.g.fillRect(ctx.x+8,yy,ctx.cw-16,52,0x10243aff);ctx.g.text(ctx.x+18,yy+8,n.label,0x7890aaff,2);ctx.g.text(ctx.x+18,yy+29,String(x.state[n.bind]??'—'),0xeaf5ffff,2);yy+=62}else if(n.kind==='button'){const top=yy;ctx.g.fillRect(ctx.x+8,top,Math.min(ctx.cw-16,260),34,0x1c547aff);ctx.g.text(ctx.x+20,top+10,n.label,0xffffffff,2);x.hits.push({x:ctx.x+8,y:top,w:Math.min(ctx.cw-16,260),h:34,action:n.action});yy+=44}else if(['row','column','card'].includes(n.kind)){if(n.kind==='card'){ctx.g.fillRect(ctx.x+4,yy,ctx.cw-8,8,0x14283dff);yy+=12}walk(n.children||[],depth+1)}}};try{walk(x.page.view||[]);x.renderMs=now()-started;x.totalExecMs+=x.renderMs;if(x.renderMs>x.page.budget.renderMs)throw this._violate(x,'render-timeout',`render completed after ${x.renderMs.toFixed(2)}ms`);if(x.totalExecMs>x.page.budget.totalMs)throw this._violate(x,'total-time',`PAGE cumulative execution exceeded ${x.page.budget.totalMs}ms`)}catch(e){ctx.g.text(ctx.x,ctx.y,'PAGE BUDGET VIOLATION',0xff8191ff,3,ctx.cw);ctx.g.text(ctx.x,ctx.y+42,String(e.message||e),0xffb0baff,2,ctx.cw)} }
  pointer(ctx){const x=this.instance(ctx.window,ctx.app);if(!x||x.suspended||ctx.event.type!=='down')return false;const h=x.hits.find(h=>ctx.event.x>=h.x&&ctx.event.x<h.x+h.w&&ctx.event.y>=h.y&&ctx.event.y<h.y+h.h);if(!h)return false;this.runAction(x,h.action).catch(e=>{this.runtime.notifications.push(ctx.app.id,'PAGE rule violation',String(e.message||e));this.runtime.desktop.invalidate()});return true;}
  stats(){return {files:this.files.size,apps:this.pagesByApp.size,violations:this.violations.length};}
}
