#include "vos/backend.hpp"
#include "vos/parser.hpp"
#include <stack>
namespace vos {
static std::vector<Token> implTokens(const std::vector<Token>&b){for(size_t i=0;i+1<b.size();++i)if(b[i].text=="__impl__"&&b[i+1].text=="{"){int d=1;std::vector<Token>r;for(size_t j=i+2;j<b.size()&&d;j++){if(b[j].text=="{")d++;else if(b[j].text=="}"){if(--d==0)break;}if(d)r.push_back(b[j]);}return r;}return b;}
static std::vector<Token> namedBlock(const std::vector<Token>&b,const std::string&name){for(size_t i=0;i+1<b.size();++i)if(b[i].text==name&&b[i+1].text=="{"){int d=1;std::vector<Token>r;for(size_t j=i+2;j<b.size()&&d;j++){if(b[j].text=="{")d++;else if(b[j].text=="}"){if(--d==0)break;}if(d)r.push_back(b[j]);}return r;}return{};}

static bool wordTok(const Token&t){return t.kind==TokKind::Identifier||t.kind==TokKind::Number||t.kind==TokKind::String||t.kind==TokKind::Character;}
std::string Backend::numberToJS(std::string s){std::string n=s; n.erase(std::remove(n.begin(),n.end(),'_'),n.end()); static const std::vector<std::pair<std::string,long double>> units={{"GiB",1073741824.0L},{"MiB",1048576.0L},{"KiB",1024.0L},{"GHz",1000000000.0L},{"MHz",1000000.0L},{"kHz",1000.0L},{"Hz",1.0L},{"ms",1000000.0L},{"us",1000.0L},{"ns",1.0L}};for(auto&[u,m]:units){if(n.size()>u.size()&&n.ends_with(u)){auto base=n.substr(0,n.size()-u.size());try{long double v=std::stold(base);return std::to_string((uint64_t)(v*m));}catch(...){}}}
  auto pos=n.find_first_not_of("0123456789abcdefABCDEFxXbB.");std::string suffix;if(pos!=std::string::npos){suffix=n.substr(pos);n=n.substr(0,pos);}if(suffix=="u64"||suffix=="i64"||suffix=="u74"||suffix=="i74"||suffix=="u96"||suffix=="u128"||suffix=="i128"||suffix=="u256")return "BigInt("+jsonEscape(n)+")";return n;}
std::string Backend::transpileExpression(const std::vector<Token>&t,size_t a,size_t b){
  if(a+4<b&&(t[a].text=="checked_cast"||t[a].text=="truncate"||t[a].text=="widen")&&t[a+1].text=="<"){
    size_t gt=a+2;int d=1;for(;gt<b;gt++){if(t[gt].text=="<")d++;else if(t[gt].text==">"&&--d==0)break;}if(gt+2<b&&t[gt+1].text=="("){
      size_t close=b-1;if(t[close].text==")"){std::string ty;for(size_t q=a+2;q<gt;q++)ty+=t[q].text;int bits=0;for(char c:ty)if(std::isdigit((unsigned char)c))bits=bits*10+(c-'0');bool sign=!ty.empty()&&ty[0]=='i';auto inner=transpileExpression(t,gt+2,close);if(t[a].text=="widen")return inner;return "runtime."+std::string(t[a].text=="checked_cast"?"checkedCast":"truncate")+"("+inner+","+std::to_string(bits)+","+(sign?"true":"false")+")";}}
  }
  if(a<b && t[a].text=="spawn" && a+1<b){
    std::string name=t[a+1].text; size_t i=a+2; std::ostringstream obj; obj<<"{"; bool first=true;
    if(i<b && t[i].text=="{"){i++;while(i<b&&t[i].text!="}"){if(t[i].kind!=TokKind::Identifier){i++;continue;}std::string key=t[i++].text;if(i<b&&(t[i].text=="="||t[i].text==":"))i++;size_t v=i;while(i<b&&t[i].text!=";"&&t[i].text!="}")i++;if(!first)obj<<",";first=false;obj<<key<<":"<<transpileExpression(t,v,i);if(i<b&&t[i].text==";")i++;}}
    obj<<"}"; return "runtime.scheduler.spawn("+jsonEscape(name)+","+obj.str()+")";
  }
  std::ostringstream o;for(size_t i=a;i<b;i++){std::string x=t[i].text;if(t[i].kind==TokKind::Number)x=numberToJS(x);else if(x=="::")x=".";else if(x=="move"||x=="borrow_dma")continue;else if(x=="checked_cast"||x=="truncate"||x=="widen"){ // casts are checked by semantic analysis; JS numeric representation is selected from target type
      if(i+1<b&&t[i+1].text=="<"){int d=0;i++;for(;i+1<b;i++){if(t[i].text=="<")d++;else if(t[i].text==">"&&--d==0)break;}continue;}
    }
    if (i > a && wordTok(t[i]) && wordTok(t[i-1]) && t[i-1].text != "move" && t[i-1].text != "borrow_dma") o << ' ';
    o << x;
  }
  return o.str();
}
std::string Backend::transpileBody(const std::vector<Token>&body,const std::string&proc,std::vector<Diagnostic>&diags){auto t=implTokens(body);auto contract=namedBlock(body,"contract");std::vector<std::vector<Token>> reqs,ensures;for(size_t c=0;c<contract.size();){if(contract[c].text=="requires"||contract[c].text=="ensures"){bool isReq=contract[c].text=="requires";size_t e=c+1;while(e<contract.size()&&contract[e].text!=";")e++;std::vector<Token>x(contract.begin()+c+1,contract.begin()+e);(isReq?reqs:ensures).push_back(std::move(x));c=e<contract.size()?e+1:e;}else c++;}std::ostringstream o;size_t i=0;int indent=1;auto ind=[&](){for(int z=0;z<indent;z++)o<<"  ";};auto untilSemi=[&](size_t s){int p=0,b=0;size_t j=s;for(;j<t.size();++j){if(t[j].text=="(")p++;else if(t[j].text==")")p--;else if(t[j].text=="[")b++;else if(t[j].text=="]")b--;if(!p&&!b&&t[j].text==";")break;}return j;};
  for(auto&rq:reqs){ind();o<<"runtime.require("<<transpileExpression(rq,0,rq.size())<<","<<jsonEscape(proc+": precondition failed")<<");\n";}
  while(i<t.size()){
    if(t[i].text=="var"||t[i].text=="bind"){bool cn=t[i].text=="bind";Span sp=t[i].span;i++;if(i>=t.size()||t[i].kind!=TokKind::Identifier){diags.push_back({Diagnostic::Level::Error,"VOS-E5000","expected variable name",sp});break;}std::string name=t[i++].text;if(i<t.size()&&t[i].text==":"){i++;int angle=0;while(i<t.size()){if(t[i].text=="<")angle++;else if(t[i].text==">")angle--;if(angle==0&&(t[i].text==":="||t[i].text=="="||t[i].text=="<-"||t[i].text==";"))break;i++;}}std::string op=i<t.size()?t[i].text:"";if(op==":="||op=="="||op=="<-")i++;size_t e=untilSemi(i);ind();o<<(cn?"const ":"let ")<<name;if(i<e)o<<" = "<<transpileExpression(t,i,e);o<<";\n";i=e<t.size()?e+1:e;continue;}
    if(t[i].text=="return"){size_t e=untilSemi(i+1);if(!ensures.empty()){ind();o<<"{\n";indent++;if(i+1<e){ind();o<<"const __vos_result = "<<transpileExpression(t,i+1,e)<<";\n";}for(auto&en:ensures){ind();o<<"runtime.require("<<transpileExpression(en,0,en.size())<<","<<jsonEscape(proc+": postcondition failed")<<");\n";}ind();o<<"return"<<(i+1<e?" __vos_result":"")<<";\n";indent--;ind();o<<"}\n";}else{ind();o<<"return";if(i+1<e)o<<' '<<transpileExpression(t,i+1,e);o<<";\n";}i=e<t.size()?e+1:e;continue;}
    if(t[i].text=="loop"&&i+1<t.size()&&t[i+1].text=="{"){ind();o<<"for (;;) {\n";indent++;i+=2;continue;}
    if(t[i].text=="when"&&i+4<t.size()&&t[i+1].kind==TokKind::Identifier&&t[i+2].text=="<-"&&t[i+3].kind==TokKind::Identifier&&t[i+4].text=="{"){ind();o<<"{\n";indent++;ind();o<<"const "<<t[i+3].text<<" = await "<<t[i+1].text<<".receive();\n";i+=5;continue;}
    if(t[i].text=="if"){size_t s=i+1;while(s<t.size()&&t[s].text!="{")s++;if(s>=t.size()){diags.push_back({Diagnostic::Level::Error,"VOS-E5001","malformed if in "+proc,t[i].span});break;}ind();o<<"if ("<<transpileExpression(t,i+1,s)<<") {\n";indent++;i=s+1;continue;}
    if(t[i].text=="}"){indent--;ind();o<<"}\n";i++;continue;}
    // VOS require condition; -> executable assertion.
    if(t[i].text=="require"){size_t e=untilSemi(i+1);ind();o<<"runtime.require("<<transpileExpression(t,i+1,e)<<","<<jsonEscape(proc+": contract requirement failed")<<");\n";i=e<t.size()?e+1:e;continue;}
    // General assignment, hardware transaction, call, atomic operation, or expression statement.
    size_t e=untilSemi(i);if(e==i){i++;continue;}if(i+3<e&&t[i].text=="cpu"&&t[i+1].text=="."&&t[i+2].text=="wait_interrupt"){ind();o<<"await cpu.wait_interrupt();\n";i=e<t.size()?e+1:e;continue;}size_t arrow=i;while(arrow<e&&t[arrow].text!="<-")arrow++;if(arrow==i+1&&t[i].kind==TokKind::Identifier){bool rhsDevice=false;for(size_t q=arrow+1;q<e;q++)if(t[q].text==".")rhsDevice=true;if(!rhsDevice){ind();o<<t[i].text<<".send("<<transpileExpression(t,arrow+1,e)<<");\n";i=e<t.size()?e+1:e;continue;}}bool hasUnsupported=false;for(size_t j=i;j<e;j++)if(t[j].text=="spawn"||t[j].text=="match"||t[j].text=="unsafe"||t[j].text=="asm"){hasUnsupported=true;diags.push_back({Diagnostic::Level::Error,"VOS-E5002","executable construct '"+t[j].text+"' requires its dedicated declaration form",t[j].span});break;}if(hasUnsupported){i=e<t.size()?e+1:e;continue;}ind();std::vector<Token>x(t.begin()+i,t.begin()+e);for(auto&z:x)if(z.text==":="||z.text=="<-")z.text="=";o<<transpileExpression(x,0,x.size())<<";\n";i=e<t.size()?e+1:e;
  }for(auto&en:ensures){ind();o<<"runtime.require("<<transpileExpression(en,0,en.size())<<","<<jsonEscape(proc+": postcondition failed")<<");\n";}return o.str();}
std::string Backend::emitManifest(const IRModule&m){return irToJson(m);}
static uint64_t extractUIntAfter(const std::vector<Token>&h,std::string_view key,uint64_t def=0){for(size_t i=0;i+1<h.size();++i)if(h[i].text==key){std::string s=h[i+1].text;s.erase(std::remove(s.begin(),s.end(),'_'),s.end());try{return s.rfind("0x",0)==0?std::stoull(s,nullptr,16):std::stoull(s);}catch(...){}}return def;}
std::string Backend::emitJS(const IRModule&m,std::vector<Diagnostic>&diags){
  std::ostringstream o;o<<"// Generated by VOS Compiler 0.3\n"<<"export async function installVOSModule(runtime) {\n"<<"  const manifest = "<<emitManifest(m)<<";\n"<<"  runtime.installManifest(manifest);\n";
  o<<"  const memory=runtime.memoryAPI, scheduler=runtime.schedulerAPI, interrupts=runtime.interruptAPI, cpu=runtime.cpuAPI, drivers=runtime.driverAPI;\n";
  o<<"  const graphics=runtime.module(\"graphics\"), display=runtime.module(\"display\"), input=runtime.module(\"input\"), filesystem=runtime.module(\"filesystem\"), terminal=runtime.module(\"terminal\"), compositor=runtime.module(\"compositor\"), desktop=runtime.module(\"desktop\"), disk=runtime.module(\"disk\"), network=runtime.module(\"network\"), audio=runtime.module(\"audio\");\n";
  for(auto&d:m.hardware.devices)o<<"  const "<<d.name<<" = runtime.device("<<jsonEscape(d.name)<<");\n";
  for(auto&d:m.metadataDecls)if(d.kind==DeclKind::Channel){uint64_t cap=1024;for(size_t q=0;q+1<d.header.size();++q)if(d.header[q].text==","){try{cap=std::stoull(d.header[q+1].text);}catch(...){cap=1024;}break;}o<<"  const "<<d.name<<" = runtime.channel("<<jsonEscape(d.name)<<","<<cap<<");\n";}
  // Process entrypoints are executable and are registered with the runtime scheduler.
  for(auto&d:m.metadataDecls)if(d.kind==DeclKind::Process){auto&t=d.body;for(size_t i=0;i<t.size();++i)if(t[i].text=="entry"&&i+1<t.size()){
      std::string entry=t[i+1].text;size_t p=i+2;while(p<t.size()&&t[p].text!="(")p++;std::vector<std::string> params;if(p<t.size()){p++;while(p<t.size()&&t[p].text!=")"){if(t[p].kind==TokKind::Identifier){params.push_back(t[p].text);while(p<t.size()&&t[p].text!=","&&t[p].text!=")")p++;if(p<t.size()&&t[p].text==",")p++;}else p++;}}
      while (p < t.size() && t[p].text != "{") p++;
      if (p >= t.size()) break;
      int dep = 1;
      std::vector<Token> b;for(size_t j=p+1;j<t.size()&&dep;j++){if(t[j].text=="{")dep++;else if(t[j].text=="}"){if(--dep==0)break;}if(dep)b.push_back(t[j]);}Token mk=d.header.front();mk.kind=TokKind::Identifier;mk.text="__impl__";Token ob=mk;ob.text="{";Token cb=mk;cb.text="}";std::vector<Token>w={mk,ob};w.insert(w.end(),b.begin(),b.end());w.push_back(cb);
      o<<"  runtime.registerProcess("<<jsonEscape(d.name)<<", async function(";for(size_t q=0;q<params.size();++q){if(q)o<<",";o<<params[q];}o<<"){\n"<<transpileBody(w,d.name+"::"+entry,diags)<<"  });\n";break;}}
  // Task declarations compile to schedulable async functions.
  for(auto&d:m.metadataDecls)if(d.kind==DeclKind::Task){Token mk=d.header.front();mk.kind=TokKind::Identifier;mk.text="__impl__";Token ob=mk;ob.text="{";Token cb=mk;cb.text="}";std::vector<Token>w={mk,ob};w.insert(w.end(),d.body.begin(),d.body.end());w.push_back(cb);o<<"  runtime.registerTask("<<jsonEscape(d.name)<<", async function(){\n"<<transpileBody(w,d.name,diags)<<"  });\n";}
  // Driver attach/detach methods are executable against the declared MMIO device.
  for(auto&d:m.metadataDecls)if(d.kind==DeclKind::Driver){std::string target;for(size_t q=0;q+2<d.header.size();++q)if(d.header[q].text=="device"&&d.header[q+1].text=="<"){target=d.header[q+2].text;break;}std::map<std::string,std::pair<std::vector<std::string>,std::vector<Token>>> methods;auto&t=d.body;for(size_t i=0;i<t.size();++i)if((t[i].text=="attach"||t[i].text=="detach")&&i+1<t.size()&&t[i+1].text=="("){std::string mn=t[i].text;size_t q=i+2;std::vector<std::string> ps;while(q<t.size()&&t[q].text!=")"){if(t[q].kind==TokKind::Identifier){ps.push_back(t[q].text);while(q<t.size()&&t[q].text!=","&&t[q].text!=")")q++;if(q<t.size()&&t[q].text==",")q++;}else q++;}if(mn=="detach"&&ps.empty())ps.push_back("device");while(q<t.size()&&t[q].text!="{")q++;if(q>=t.size())continue;int dep=1;std::vector<Token>b;for(size_t z=q+1;z<t.size()&&dep;z++){if(t[z].text=="{")dep++;else if(t[z].text=="}"){if(--dep==0)break;}if(dep)b.push_back(t[z]);}methods[mn]={ps,b};}
    o<<"  runtime.registerDriver("<<jsonEscape(d.name)<<","<<jsonEscape(target)<<",{";bool first=true;for(auto&[mn,mb]:methods){if(!first)o<<",";first=false;o<<mn<<":async function(";for(size_t z=0;z<mb.first.size();++z){if(z)o<<",";o<<mb.first[z];}o<<"){\n";Token mk=d.header.front();mk.kind=TokKind::Identifier;mk.text="__impl__";Token ob=mk;ob.text="{";Token cb=mk;cb.text="}";std::vector<Token>w={mk,ob};w.insert(w.end(),mb.second.begin(),mb.second.end());w.push_back(cb);o<<transpileBody(w,d.name+"::"+mn,diags)<<"  }";}o<<"});\n";}
  // State-machine transitions become executable runtime transition tables.
  for(auto&d:m.metadataDecls)if(d.kind==DeclKind::Machine){auto&t=d.body;std::string initial;for(size_t i=0;i+1<t.size();++i)if(t[i].text=="state"&&t[i+1].kind==TokKind::Identifier){initial=t[i+1].text;break;}o<<"  { const __transitions=new Map();\n";for(size_t i=0;i+5<t.size();++i)if(t[i].kind==TokKind::Identifier&&t[i+1].text=="--["){std::string from=t[i].text;size_t evs=i+2,eve=evs;while(eve<t.size()&&t[eve].text!="]")eve++;if(eve+2>=t.size()||t[eve+1].text!="-->"||t[eve+2].kind!=TokKind::Identifier)continue;std::string event=tokensToSource(std::vector<Token>(t.begin()+evs,t.begin()+eve));for(size_t p=0;(p=event.find("::",p))!=std::string::npos;)event.replace(p,2,".");std::string to=t[eve+2].text;size_t q=eve+3;while(q<t.size()&&t[q].text!="{")q++;std::vector<Token>b;if(q<t.size()){int dep=1;for(size_t z=q+1;z<t.size()&&dep;z++){if(t[z].text=="{")dep++;else if(t[z].text=="}"){if(--dep==0)break;}if(dep)b.push_back(t[z]);}}Token mk=d.header.front();mk.kind=TokKind::Identifier;mk.text="__impl__";Token ob=mk;ob.text="{";Token cb=mk;cb.text="}";std::vector<Token>w={mk,ob};w.insert(w.end(),b.begin(),b.end());w.push_back(cb);o<<"    __transitions.set("<<jsonEscape(from+":"+event)<<",{to:"<<jsonEscape(to)<<",action:async function(payload){\n"<<transpileBody(w,d.name+"::"+from,diags)<<"    }});\n";i=q;}o<<"    runtime.registerStateMachine("<<jsonEscape(d.name)<<","<<jsonEscape(initial)<<",__transitions); }\n";}
  // Procedures without suspension points stay synchronous; procedures using wait_interrupt/spawn become async.
  auto needsAsync=[](const std::vector<Token>&b){for(auto&x:b)if(x.text=="wait_interrupt"||x.text=="spawn"||x.text=="when")return true;return false;};
  for(auto&f:m.functions){o<<"  "<<(needsAsync(f.body)?"async ":"")<<"function "<<f.name<<"(";for(size_t i=0;i<f.params.size();++i){if(i)o<<",";o<<f.params[i].first;}o<<"){\n"<<transpileBody(f.body,f.name,diags)<<"  }\n";}
  for(auto&f:m.functions)o<<"  runtime.registerProcedure("<<jsonEscape(f.name)<<","<<f.name<<");\n";
  for(auto&d:m.metadataDecls){if(d.kind==DeclKind::Interrupt){uint64_t v=extractUIntAfter(d.header,"vector",0);o<<"  runtime.registerInterrupt("<<v<<","<<jsonEscape(d.name)<<", async function(){\n";std::vector<Token> fake=d.body; Token mk=d.header.front();mk.kind=TokKind::Identifier;mk.text="__impl__";Token ob=mk;ob.text="{";Token cb=ob;cb.text="}";std::vector<Token>w={mk,ob};w.insert(w.end(),fake.begin(),fake.end());w.push_back(cb);o<<transpileBody(w,d.name,diags);o<<"  });\n";}}
  o<<"  return manifest;\n}\n";return o.str();
}
// ---- tiny real WebAssembly backend for pure i32 procedures ----
namespace {
void leb(std::vector<uint8_t>&o,uint32_t v){do{uint8_t b=v&0x7f;v>>=7;if(v)b|=0x80;o.push_back(b);}while(v);}void sleb(std::vector<uint8_t>&o,int32_t v){bool more=true;while(more){uint8_t b=v&0x7f;v>>=7;bool sign=b&0x40;more=!((v==0&&!sign)||(v==-1&&sign));if(more)b|=0x80;o.push_back(b);}}
void section(std::vector<uint8_t>&o,uint8_t id,const std::vector<uint8_t>&p){o.push_back(id);leb(o,p.size());o.insert(o.end(),p.begin(),p.end());}
struct EParser{const std::vector<Token>&t;size_t i=0,e=0;std::unordered_map<std::string,uint32_t> locals;bool ok=true;std::vector<uint8_t> code;int prec(std::string x){if(x=="|"||x=="^")return 1;if(x=="&")return 2;if(x=="<<"||x==">>")return 3;if(x=="+"||x=="-")return 4;if(x=="*"||x=="/")return 5;return -1;}void primary(){if(i>=e){ok=false;return;}auto x=t[i++];if(x.text=="("){expr(0);if(i>=e||t[i++].text!=")")ok=false;return;}if(x.kind==TokKind::Number){std::string s=x.text;s.erase(std::remove(s.begin(),s.end(),'_'),s.end());auto p=s.find_first_not_of("0123456789");if(p!=std::string::npos)s=s.substr(0,p);try{code.push_back(0x41);sleb(code,(int32_t)std::stoll(s));}catch(...){ok=false;}return;}auto it=locals.find(x.text);if(it!=locals.end()){code.push_back(0x20);leb(code,it->second);return;}ok=false;}void expr(int minp){primary();while(i<e){std::string op=t[i].text;int p=prec(op);if(p<minp)break;i++;expr(p+1);uint8_t w=0;if(op=="+")w=0x6a;else if(op=="-")w=0x6b;else if(op=="*")w=0x6c;else if(op=="/")w=0x6e;else if(op=="&")w=0x71;else if(op=="|")w=0x72;else if(op=="^")w=0x73;else if(op=="<<")w=0x74;else if(op==">>")w=0x76;else{ok=false;return;}code.push_back(w);}}};
}
std::vector<uint8_t> Backend::emitWasm(const IRModule&m,std::set<std::string>&exported,std::vector<Diagnostic>&){struct WF{const IRFunction*f;std::vector<uint8_t>code;};std::vector<WF>fs;for(auto&f:m.functions){if(!f.pure)continue;bool types=f.returnType=="u32"||f.returnType=="i32";for(auto&p:f.params)types&=(p.second=="u32"||p.second=="i32");if(!types)continue;auto b=implTokens(f.body);size_t r=0;while(r<b.size()&&b[r].text!="return")r++;if(r==b.size())continue;size_t e=r+1;while(e<b.size()&&b[e].text!=";")e++;EParser ep{b,r+1,e,{},true,{}};for(size_t i=0;i<f.params.size();++i)ep.locals[f.params[i].first]=i;ep.expr(0);if(!ep.ok||ep.i!=e)continue;ep.code.push_back(0x0b);fs.push_back({&f,std::move(ep.code)});exported.insert(f.name);}std::vector<uint8_t>o={0,97,115,109,1,0,0,0};if(fs.empty())return o;
  std::vector<uint8_t>types;leb(types,fs.size());for(auto&x:fs){types.push_back(0x60);leb(types,x.f->params.size());for(size_t i=0;i<x.f->params.size();++i)types.push_back(0x7f);leb(types,1);types.push_back(0x7f);}section(o,1,types);
  std::vector<uint8_t>func;leb(func,fs.size());for(uint32_t i=0;i<fs.size();++i)leb(func,i);section(o,3,func);
  std::vector<uint8_t>ex;leb(ex,fs.size());for(uint32_t i=0;i<fs.size();++i){leb(ex,fs[i].f->name.size());ex.insert(ex.end(),fs[i].f->name.begin(),fs[i].f->name.end());ex.push_back(0);leb(ex,i);}section(o,7,ex);
  std::vector<uint8_t>codes;leb(codes,fs.size());for(auto&x:fs){std::vector<uint8_t>b;leb(b,0);b.insert(b.end(),x.code.begin(),x.code.end());leb(codes,b.size());codes.insert(codes.end(),b.begin(),b.end());}section(o,10,codes);return o;}
std::string Backend::emitDebug(const IRModule&m){std::ostringstream o;o<<"{\"sourceHash\":"<<jsonEscape(m.sourceHash)<<",\"symbols\":[";for(size_t i=0;i<m.functions.size();++i){if(i)o<<",";o<<"{\"name\":"<<jsonEscape(m.functions[i].name)<<",\"kind\":\"procedure\"}";}o<<"]}";return o.str();}
std::string Backend::emitLibrary(const IRModule&m){std::ostringstream o;o<<"{\"module\":"<<jsonEscape(m.name)<<",\"abi\":1,\"exports\":[";for(size_t i=0;i<m.functions.size();++i){if(i)o<<",";o<<jsonEscape(m.functions[i].name);}o<<"]}";return o.str();}

std::vector<uint8_t> Backend::assembleV74(const IRModule&m,std::vector<Diagnostic>&diags){
  std::vector<uint8_t> out;auto emit74=[&](uint64_t v){for(int i=0;i<10;i++)out.push_back(i<8?(uint8_t)(v>>(8*i)):0);};
  auto reg=[&](const Token&t)->int{if(t.kind!=TokKind::Identifier)return -1;std::string x=t.text;if(x=="fp")return 29;if(x=="sp")return 30;if(x=="lr")return 31;if(x.size()>1&&x[0]=='r'){try{int n=std::stoi(x.substr(1));return n>=0&&n<32?n:-1;}catch(...){}}return -1;};
  auto num=[&](const Token&t,bool&ok)->uint64_t{ok=false;std::string x=t.text;x.erase(std::remove(x.begin(),x.end(),'_'),x.end());for(size_t p=1;p<x.size();++p)if((x[p]=='u'||x[p]=='i')&&p+1<x.size()&&std::all_of(x.begin()+p+1,x.end(),[](char c){return std::isdigit((unsigned char)c);}))x.resize(p);try{uint64_t v=x.rfind("0x",0)==0?std::stoull(x,nullptr,16):std::stoull(x,nullptr,10);ok=true;return v;}catch(...){return 0;}};
  for(auto&d:m.metadataDecls)if(d.kind==DeclKind::Assembly){auto t=implTokens(d.body);size_t i=0;while(i<t.size()){while(i<t.size()&&t[i].text==";")i++;if(i>=t.size())break;Token mn=t[i++];std::string op=mn.text;std::vector<Token>a;while(i<t.size()&&t[i].text!=";"){if(t[i].text!=","&&t[i].text!="["&&t[i].text!="]")a.push_back(t[i]);i++;}if(i<t.size())i++;auto bad=[&](std::string msg){diags.push_back({Diagnostic::Level::Error,"VOS-E5100","V74 assembler: "+msg,mn.span});};
      static const std::unordered_map<std::string,uint8_t> rr={{"ADD",0xA0},{"SUB",0xA1},{"MUL",0xA2},{"DIV",0xA3},{"AND",0xA4},{"OR",0xA5},{"XOR",0xA6},{"SHL",0xA7},{"SHR",0xA8},{"CMP",0xA9}};
      static const std::unordered_map<std::string,uint8_t> br={{"JMP",0xB0},{"JZ",0xB1},{"JNZ",0xB2},{"JC",0xB3},{"JNC",0xB4},{"CALL",0xB5}};
      if(op=="NOP"){out.push_back(0x00);continue;} if(op=="HLT"){out.push_back(0xFF);continue;} if(op=="RET"){out.push_back(0xB6);continue;} if(op=="PUSHF"){out.push_back(0x22);continue;} if(op=="POPF"){out.push_back(0x23);continue;} if(op=="IRET"){out.push_back(0xCE);continue;}
      if(op=="MOV"&&a.size()==2){int r0=reg(a[0]),r1=reg(a[1]);if(r0<0||r1<0){bad("MOV requires two registers");continue;}out.push_back(0x10);out.push_back((r0<<4)|r1);continue;}
      if(op=="MOVI"&&a.size()==2){int r0=reg(a[0]);bool ok=false;auto v=num(a[1],ok);if(r0<0||!ok){bad("MOVI requires register, immediate");continue;}out.push_back(0x11);out.push_back(r0);emit74(v);continue;}
      if((op=="LOAD"||op=="STORE")&&a.size()==2){int r0=reg(a[0]),r1=reg(a[1]);if(r0<0||r1<0){bad(op+" requires registers");continue;}out.push_back(op=="LOAD"?0x12:0x13);out.push_back((r0<<4)|r1);continue;}
      if((op=="PUSH"||op=="POP")&&a.size()==1){int r0=reg(a[0]);if(r0<0){bad(op+" requires register");continue;}out.push_back(op=="PUSH"?0x20:0x21);out.push_back(r0);continue;}
      if(rr.count(op)&&a.size()==2){int r0=reg(a[0]),r1=reg(a[1]);if(r0<0||r1<0){bad(op+" requires two registers");continue;}out.push_back(rr.at(op));out.push_back((r0<<4)|r1);continue;}
      if(br.count(op)&&a.size()==1){bool ok=false;auto v=num(a[0],ok);if(!ok){bad(op+" requires numeric address");continue;}out.push_back(br.at(op));emit74(v);continue;}
      if(op=="INT"&&a.size()==1){bool ok=false;auto v=num(a[0],ok);if(!ok||v>255){bad("INT requires vector 0..255");continue;}out.push_back(0xCD);out.push_back((uint8_t)v);continue;}
      if((op=="IN"||op=="OUT")&&a.size()==2){int r0=reg(a[0]);bool ok=false;auto v=num(a[1],ok);if(r0<0||!ok){bad(op+" requires register, port");continue;}out.push_back(op=="IN"?0xEE:0xEF);out.push_back(r0);emit74(v);continue;}
      bad("unknown or malformed instruction '"+op+"'");
    }}return out;
}

BuildProducts Backend::build(const IRModule&m,int){BuildProducts p;p.manifest=emitManifest(m);std::set<std::string>wexp;p.wasm=emitWasm(m,wexp,p.diagnostics);p.js=emitJS(m,p.diagnostics);p.asmV74=assembleV74(m,p.diagnostics);p.debugJson=emitDebug(m);p.libraryJson=emitLibrary(m);auto bytes=[](std::string s){return std::vector<uint8_t>(s.begin(),s.end());};p.vhw=makeContainer("VHW0",1,0,{{"manifest",bytes(p.manifest)}});p.vlib=makeContainer("VLIB",1,0,{{"exports",bytes(p.libraryJson)},{"wasm",p.wasm},{"asm.v74",p.asmV74}});p.vdbg=makeContainer("VDBG",1,0,{{"symbols",bytes(p.debugJson)}});p.vimg=makeContainer("VIMG",1,0,{{"manifest",bytes(p.manifest)},{"module.js",bytes(p.js)},{"module.wasm",p.wasm},{"asm.v74",p.asmV74}});p.vxe=makeContainer("VXE0",1,0,{{"manifest",bytes(p.manifest)},{"module.js",bytes(p.js)},{"module.wasm",p.wasm},{"asm.v74",p.asmV74},{"debug",bytes(p.debugJson)}});return p;}
}
