#include "vos/ir.hpp"
#include "vos/parser.hpp"
namespace vos {
IRModule Lowerer::lower(const SemanticModel&m){IRModule x;x.name=m.hw.name;x.version=m.program.vosVersion;x.architecture=m.hw.architecture;x.domain=m.domain;x.sourceHash=hex64(fnv1a64(readText(m.program.file)));x.hardware=m.hw;for(auto&p:m.procs)x.functions.push_back({p.name,p.returnType,p.pure,p.params,p.body,p.effects});for(auto&d:m.program.decls)if(d.kind!=DeclKind::Procedure)x.metadataDecls.push_back(d);return x;}
void Optimizer::optimize(IRModule&m,int level){if(level<=0)return;for(auto&f:m.functions){std::vector<Token> out;out.reserve(f.body.size());for(size_t i=0;i<f.body.size();++i){if(i+2<f.body.size()&&f.body[i].kind==TokKind::Number&&(f.body[i+1].text=="+"||f.body[i+1].text=="-"||f.body[i+1].text=="*")&&f.body[i+2].kind==TokKind::Number){try{long long a=std::stoll(f.body[i].text),b=std::stoll(f.body[i+2].text),v=0;if(f.body[i+1].text=="+")v=a+b;else if(f.body[i+1].text=="-")v=a-b;else v=a*b;Token t=f.body[i];t.text=std::to_string(v);out.push_back(t);i+=2;continue;}catch(...){}}out.push_back(f.body[i]);}f.body.swap(out);}}
static std::string jprop(const std::map<std::string,std::string>&m){std::ostringstream o;o<<"{";bool first=true;for(auto&[k,v]:m){if(!first)o<<",";first=false;o<<jsonEscape(k)<<":"<<jsonEscape(v);}o<<"}";return o.str();}
static std::map<std::string,std::string> flatProps(const std::vector<Token>&t){std::map<std::string,std::string> p;for(size_t i=0;i<t.size();){if(t[i].kind!=TokKind::Identifier){++i;continue;}std::string key=t[i++].text;if(i<t.size()&&t[i].text=="=")++i;size_t s=i;int dep=0;while(i<t.size()){if(t[i].text=="("||t[i].text=="["||t[i].text=="<")++dep;else if(t[i].text==")"||t[i].text=="]"||t[i].text==">")--dep;if(dep==0&&t[i].text==";")break;++i;}std::vector<Token> v(t.begin()+static_cast<long>(s),t.begin()+static_cast<long>(i));p[key]=tokensToSource(v);if(i<t.size()&&t[i].text==";")++i;}return p;}
static std::string scalar(std::string v){if(v.size()>=2&&((v.front()=='"'&&v.back()=='"')||(v.front()=='\''&&v.back()=='\'')))return v.substr(1,v.size()-2);return v;}
static std::string appJson(const Decl&d){auto p=flatProps(d.body);auto get=[&](std::string k,std::string fallback){auto it=p.find(k);return scalar(it==p.end()?fallback:it->second);};std::string renderer=get("renderer",get("kind","panel"));std::ostringstream o;o<<"{"<<"\"id\":"<<jsonEscape(get("id",d.name))<<",\"title\":"<<jsonEscape(get("title",d.name))<<",\"renderer\":"<<jsonEscape(renderer)<<",\"kind\":"<<jsonEscape(renderer)<<",\"icon\":"<<jsonEscape(get("icon","APP"))<<",\"description\":"<<jsonEscape(get("description",""))<<",\"width\":"<<jsonEscape(get("width","640"))<<",\"height\":"<<jsonEscape(get("height","420"))<<",\"singleton\":"<<jsonEscape(get("singleton","true"))<<",\"desktop\":"<<jsonEscape(get("desktop","true"))<<",\"capabilities\":"<<jsonEscape(get("capabilities",""))<<",\"accent\":"<<jsonEscape(get("accent","0x69B7FFFF"))<<",\"content\":"<<jsonEscape(get("content",""))<<",\"file\":"<<jsonEscape(get("file",""))<<",\"url\":"<<jsonEscape(get("url",""))<<",\"command\":"<<jsonEscape(get("command",""))<<",\"shortcut\":"<<jsonEscape(get("shortcut",""))<<",\"category\":"<<jsonEscape(get("category","custom"))<<",\"source\":"<<jsonEscape(d.name)<<"}";return o.str();}
std::string irToJson(const IRModule&m){std::ostringstream o;o<<"{\n  \"name\":"<<jsonEscape(m.name)<<",\n  \"version\":"<<jsonEscape(m.version)<<",\n  \"architecture\":"<<jsonEscape(m.architecture)<<",\n  \"domain\":"<<jsonEscape(m.domain)<<",\n  \"sourceHash\":"<<jsonEscape(m.sourceHash)<<",\n  \"abi\":2,\n  \"hardware\":{\n    \"components\":[";for(size_t i=0;i<m.hardware.components.size();++i){auto&c=m.hardware.components[i];if(i)o<<",";o<<"{\"kind\":"<<jsonEscape(c.kind)<<",\"name\":"<<jsonEscape(c.name)<<",\"properties\":"<<jprop(c.properties)<<"}";}o<<"],\n    \"regions\":[";for(size_t i=0;i<m.hardware.regions.size();++i){auto&r=m.hardware.regions[i];if(i)o<<",";o<<"{\"name\":"<<jsonEscape(r.name)<<",\"address\":"<<r.address<<",\"size\":"<<r.size<<",\"alignment\":"<<r.alignment<<",\"permissions\":"<<jsonEscape(r.permissions)<<",\"cache\":"<<jsonEscape(r.cache)<<",\"mapping\":"<<jsonEscape(r.mapping)<<"}";}o<<"],\n    \"devices\":[";for(size_t i=0;i<m.hardware.devices.size();++i){auto&d=m.hardware.devices[i];if(i)o<<",";o<<"{\"name\":"<<jsonEscape(d.name)<<",\"mmioBase\":"<<d.mmioBase<<",\"mmioSize\":"<<d.mmioSize<<",\"registers\":[";for(size_t j=0;j<d.registers.size();++j){auto&r=d.registers[j];if(j)o<<",";o<<"{\"name\":"<<jsonEscape(r.name)<<",\"type\":"<<jsonEscape(r.type)<<",\"offset\":"<<r.offset<<",\"access\":"<<jsonEscape(r.access)<<",\"reset\":"<<r.reset<<",\"volatile\":"<<(r.isVolatile?"true":"false")<<"}";}o<<"]}";}o<<"]},\n  \"apps\":[";bool af=false;for(auto&d:m.metadataDecls)if(d.kind==DeclKind::App){if(af)o<<",";af=true;o<<appJson(d);}o<<"],\n  \"functions\":[";for(size_t i=0;i<m.functions.size();++i){auto&f=m.functions[i];if(i)o<<",";o<<"{\"name\":"<<jsonEscape(f.name)<<",\"returnType\":"<<jsonEscape(f.returnType)<<",\"pure\":"<<(f.pure?"true":"false")<<",\"effects\":[";size_t j=0;for(auto&e:f.effects){if(j++)o<<",";o<<jsonEscape(e);}o<<"]}";}o<<"],\n  \"metadata\":[";for(size_t i=0;i<m.metadataDecls.size();++i){auto&d=m.metadataDecls[i];if(i)o<<",";o<<"{\"kind\":"<<jsonEscape(declKindName(d.kind))<<",\"name\":"<<jsonEscape(d.name)<<",\"header\":"<<jsonEscape(tokensToSource(d.header))<<",\"body\":"<<jsonEscape(tokensToSource(d.body))<<"}";}o<<"]\n}";return o.str();}
}
